#!/bin/bash

set -e

pushd "$(dirname $0)" > /dev/null

if [[ $1 == '--self-update' ]]; then
	curl 'https://raw.githubusercontent.com/chefkoch-dev/docker-run/master/run' -o run
	exit
fi

options=''
[[ -n ${SSH_AUTH_SOCK} ]] && options+=" -v ${SSH_AUTH_SOCK}:/run/ssh.sock -e SSH_AUTH_SOCK=/run/ssh.sock"

CACHE_CONTAINER=cache-container-$(pwd | sha1sum | awk '{print $1}')

if ! docker ps -a --no-trunc | grep -q "${CACHE_CONTAINER}"; then
    docker run -v ${HOME%/*} -v /root --name=${CACHE_CONTAINER} busybox chmod 1777 ${HOME%/*}
fi

docker run --rm \
    -v $(pwd)/../:/app \
    -w /app \
    --volumes-from=${CACHE_CONTAINER} \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v /run/docker.sock:/run/docker.sock \
    -u $(id -u) \
    ${options} \
    "$@"
